apiVersion: v1
kind: Service
metadata:
  name: ir-messaging
  labels:
    app: ir-messaging
spec:
  type: NodePort
  ports:
  - name: server
    port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    app: ir-messaging
