apiVersion: v1
kind: Service
metadata:
  name: ir-property-rental
  labels:
    app: ir-property-rental
spec:
  type: NodePort
  ports:
  - name: server
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: ir-property-rental
