apiVersion: v1
kind: Service
metadata:
  name: ir-property-listing
  labels:
    app: ir-property-listing
spec:
  type: NodePort
  ports:
  - name: server
    port: 8084
    protocol: TCP
    targetPort: 8084
  selector:
    app: ir-property-listing
