apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ir-property-catalogue
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ir-property-catalogue
    spec:
      containers:
      - image: jm5619/ir-property-catalogue
        name: ir-property-catalogue
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: minikube
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
        livenessProbe:
        ports:
        - containerPort: 8081
          name: server
          protocol: TCP
