apiVersion: v1
kind: Service
metadata:
  name: ir-property-catalogue
  labels:
    app: ir-property-catalogue
spec:
  type: NodePort
  ports:
  - name: server
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: ir-property-catalogue
