apiVersion: v1
kind: Service
metadata:
  name: ir-recommendation
  labels:
    app: ir-recommendation
spec:
  type: NodePort
  ports:
  - name: server
    port: 8087
    protocol: TCP
    targetPort: 8087
  selector:
    app: ir-recommendation
