apiVersion: v1
kind: Service
metadata:
  name: ir-user
  labels:
    app: ir-user
spec:
  type: NodePort
  ports:
  - name: server
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ir-user
